version: '3'

services:
  fastfeet-db:
    image: postgres:15-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=fastfeet
    volumes:
      - pgdata_fastfeet:/var/lib/postgresql/data

volumes:
  pgdata_fastfeet:
